### ISSUE TITLE
Modules are being pushed to Canvas as "unpublished"

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA-LTI#54]
Originally, it seemed to only be happening when an existing course had modules added. But the newly created PL book had no modules published.

**Comment by hosamshahin** [comment]
It happened that Taylor was creating the TL book at the same time I was deploying and testing changes to publish newly added modules. The issue was fixed and tested, the entire book will be published once created and only newly added modules will be published. However, any modules intentionally unpublished by instructors won't be republished by the course creation script.

**Comment by cashaffer** [comment]
I just pushed an update to the CS4104 config and courses (both at canvas.instructure.com and at canvas.vt.edu). The new modules were NOT published.

Also, a module that got dropped WAS still published, but I think that you might be doing intentionally.

**Comment by cashaffer** [comment]
Today when I pushed some new module to CS4104, they showed up as "published". Is this problem fixed now?

**Comment by hosamshahin** [comment]
Yes, I fixed this issue back then and I forgot to mention this issue in the commit.
